### ISSUE TITLE
Convert Freight Train

### ISSUE THREAD

**Issue by codeadamca** [BrickMMO/hackathon-set#8]
Convert the "Freight Train" PDF results to Markdown. 

Use the "12 Grimmauld Place" as an example:
https://brickmmo.github.io/hackathon-set/12-grimmauld-place

**Comment by codeadamca** [comment]
@SravaniSingani Can you add a link to your new page from this page:

https://github.com/BrickMMO/hackathon-set/blob/main/index.markdown

**Comment by SravaniSingani** [comment]
Hi Adam!

I just needed one clarification. Do I need to add the link of
index.markdown at the end of the page in carwash.markdown?
